- name: Faz o clone do repositório do st
  git:
    repo: https://git.suckless.org/st
    dest: "/home/{{ usuario }}/.config/suckless/st/"
    clone: yes
    force: yes
  become: yes
  become_user: "{{ usuario }}"

- name: Copia arquivo de configuração do st
  copy:
    src: "config.def.h"
    dest: "/home/{{ usuario }}/.config/suckless/st/"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"

- name: Compila o st
  shell: |
    cd "/home/{{ usuario }}/.config/suckless/st"
    make
    make clean install
  
