- name: Remove diretório do st
  file:
    path: "/home/{{ usuario }}/.config/suckless/st"
    state: absent
  become: yes
  become_user: root

- name: Clona o repositório do st-0.9
  git:
    repo: https://github.com/Crystian0704/st.git
    dest: /home/{{ usuario }}/.config/suckless/st
    clone: yes
  become: yes
  become_user: "{{ usuario }}"

- name: Compila o st
  shell: |
    rm -rf "/usr/local/bin/st"
    cd "/home/{{ usuario }}/.config/suckless/st"
    make
    make install
