[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Crystian", email = "crystian.alexsander@gmail.com"},
    {name = "", email = ""},
]
dependencies = [
    "ansible>=8.2.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

