[project]
name = ""
version = ""
description = ""
authors = [
    {name = "capereira", email = "ti11@casajoka.com.br"},
    {name = "", email = ""},
]
dependencies = [
    "ansible>=8.2.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

