all:
  hosts:
    vault1:
      ansible_host: 192.168.121.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/vms/vault/.vagrant/machines/vault1/libvirt/private_key 
    vault2:
      ansible_host: 192.168.121.3
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/vms/vault/.vagrant/machines/vault2/libvirt/private_key
    vault3:
      ansible_host: 192.168.121.4
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/vms/vault/.vagrant/machines/vault3/libvirt/private_key
    debian:
      ansible_host: 192.168.122.40
      ansible_user: root

  children:
    vault:
      hosts:
        vault1:
        vault2:
        vault3:
