all:
  hosts:
    vault1:
      ansible_host: 192.168.121.2
      ansible_user: vagrant
      ansible_hostname: vault1
    vault2:
      ansible_host: 192.168.121.3
      ansible_user: vagrant
      ansible_hostname: vault2

    vault3:
      ansible_host: 192.168.121.4
      ansible_user: vagrant
      ansible_hostname: vault3
  children:
    vault:
      hosts:
        vault1:
        vault2:
        vault3:
