all:
  hosts:
    vault1:
      ansible_host: 192.168.121.2
    vault2:
      ansible_host: 192.168.121.3
    vault3:
      ansible_host: 192.168.121.4

    debian:
      ansible_host: 192.168.122.140
      ansible_user: root

  children:
    vault:
      hosts:
        vault1:
        vault2:
        vault3:
