- name: Instala xbindkeys
  apt:
    name: xbindkeys
    state: present
    update_cache: yes

- name: Copia .xbindkeysrc
  copy:
    src: files/.xbindkeysrc
    dest: "/home/{{ usuario }}/.xbindkeysrc"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0644

- name: Copia atalho-info-bateria.sh para /usr/local/bin
  copy:
    src: files/atalho-info-bateria.sh
    dest: /usr/local/bin/atalho-info-bateria.sh
    owner: root
    group: root
    mode: 0755

- name: Executa xbindkeys
  command: xbindkeys