---

- name: Instalação das dependências
  apt:
    name:
      - make
      - gcc
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - git
    state: latest
    type: package

- name: Clona o repositório do dwm
  git:
    repo: https://git.suckless.org/dwm
    dest: /home/{{ user }}/.config/
    clone: yes

- name: Copia o diretorio patches
  copy:
    src: {{ item }}
    dest: /home/{{ user }}/dwm
    owner: "{{ user }}"
    group: "{{ user }}"
    loop:
      - patches_autostart_dwm-autostart-20161205-bb3bd6f.diff
      - patches_fullgaps_dwm-fullgaps-20200508-7b77734.diff

- name: Aplica patch
  shell: |
    cd /home/{{ user }}/.config/dwm
    patch < /home/{{ user }}/dwm/config/config.patch