- name: Remove diretório do dwm
  file:
    path: "/home/{{ usuario }}/.config/suckless/dwm"
    state: absent
  become: yes
  become_user: root

- name: Copia o arquivo .Xresources
  copy:
    src: .Xresources
    dest: /home/{{ usuario }}/
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0644

- name: Copia o arquivo xmenu-start.sh e da permissão de execução
  copy:
    src: xmenu-start.sh
    dest: "/usr/local/bin/xmenu-start"
    mode: 0755


- name: Copia o arquivo autostart.sh e da permissão de execução
  copy:
    src: autostart.sh
    dest: /home/{{ usuario }}/.dwm/
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0755

- name: Copia o arquivo dwm.desktop
  copy:
    src: dwm.desktop
    dest: /usr/share/xsessions
    owner: root
    group: root
    mode: 0644

- name: Clona o repositório do dwm-6.4
  git:
    repo: https://github.com/Crystian0704/dwm.git
    dest: /home/{{ usuario }}/.config/suckless/dwm
    clone: yes

- name: Compila o dwm
  shell: |
    rm -rf "/usr/local/bin/dwm"
    cd "/home/{{ usuario }}/.config/suckless/dwm"
    make
    make install
    


