---
- name: Instalação das dependências
  apt:
    name:
      - make
      - gcc
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - git
    state: present
  become: yes

- name: Cria pasta .config no diretório do usuário se não existir
  file:
    path: /home/{{ user }}/.config
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  
- name: Clona o repositório do dwm
  ansible.builtin.git:
    repo: https://git.suckless.org/dwm
    dest: /home/{{ user }}/.config/dwm
    clone: yes

- name: Remove o arquivo .git 
  file:
    path: /home/{{ user }}/.config/dwm/.git
    state: absent

- name: Altera dono e grupo dos arquivos do dwm
  file:
    path: /home/{{ user }}/.config/dwm
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes

- name: Copia o diretorio patches
  copy:
    src: patches/
    dest: /home/{{ user }}/.config/dwm
    owner: "{{ user }}"
    group: "{{ user }}"

