- name: Remove diretório do dwm
  file:
    path: "/home/{{ usuario }}/.config/suckless/dwm"
    state: absent
  become: yes
  become_user: root

- name: Copia o arquivo autostart.sh e da permissão de execução
  copy:
    src: autostart.sh
    dest: /home/{{ usuario }}/.dwm/
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0755

- name: Copia o arquivo dwm.desktop
  copy:
    src: dwm.desktop
    dest: /usr/share/xsessions
    owner: root
    group: root
    mode: 0644

- name: Clona o repositório do dwm
  git:
    repo: https://git.suckless.org/dwm
    dest: /home/{{ usuario }}/.config/suckless/dwm
    clone: yes
    force: yes
  become: yes
  become_user: "{{ usuario }}"

- name: Baixa os patches
  uri:
    url: "{{ item.src }}"
    dest: "/home/{{ usuario }}/.config/suckless/dwm/{{ item.filename }}"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
  loop:
    - {
        src: "https://dwm.suckless.org/patches/autostart/dwm-autostart-20161205-bb3bd6f.diff",
        filename: "dwm-autostart-20161205-bb3bd6f.diff"
      }
    - {
        src: "https://dwm.suckless.org/patches/centeredwindowname/dwm-centeredwindowname-20200723-f035e1e.diff",
        filename: "dwm-centeredwindowname-20200723-f035e1e.diff"
      }
    - {
        src: "https://dwm.suckless.org/patches/vanitygaps/dwm-cfacts-vanitygaps-6.4_combo.diff",
        filename: "dwm-cfacts-vanitygaps-6.4_combo.diff"
      }
    - {
        src: "https://dwm.suckless.org/patches/hide_vacant_tags/dwm-hide_vacant_tags-6.3.diff",
        filename: "dwm-hide_vacant_tags-6.3.diff"
      }
    - {
        src: "https://dwm.suckless.org/patches/rotatestack/dwm-rotatestack-20161021-ab9571b.diff",
        filename: "dwm-rotatestack-20161021-ab9571b.diff"
      }
- name: Aplica os patches
  shell: |
    cd "/home/{{ usuario }}/.config/suckless/dwm"
    patch < dwm-rotatestack-20161021-ab9571b.diff
    patch < dwm-autostart-20161205-bb3bd6f.diff
    patch < dwm-cfacts-vanitygaps-6.4_combo.diff
    patch < dwm-centeredwindowname-20200723-f035e1e.diff
    patch < dwm-hide_vacant_tags-6.3.diff


- name: Copia o arquivo de configuração
  copy:
    src: config.def.h
    dest: /home/{{ usuario }}/.config/suckless/dwm
    owner: "{{ usuario }}"
    group: "{{ usuario }}"

- name: Compila o dwm
  shell: |
    rm -rf "/usr/local/bin/dwm"
    cd "/home/{{ usuario }}/.config/suckless/dwm"
    make
    make install


