- name: Copia o arquivo autostart.sh e da permissão de execução
  copy:
    src: autostart.sh
    dest: /home/{{ usuario }}/.dwm/
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0755

- name: Copia o arquivo dwm.desktop
  copy:
    src: dwm.desktop
    dest: /usr/share/xsessions
    owner: root
    group: root
    mode: 0644

- name: Clona o repositório do dwm
  git:
    repo: https://git.suckless.org/dwm
    dest: /home/{{ usuario }}/.config/suckless/dwm
    clone: yes
    force: yes
  become: yes
  become_user: "{{ usuario }}"

- name: Baixa os patches
  uri:
    url: "{{ item.src }}"
    dest: "/home/{{ usuario }}/.config/suckless/dwm/{{ item.filename }}"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
  loop:
    - {
        src: "https://dwm.suckless.org/patches/autostart/dwm-autostart-20161205-bb3bd6f.diff",
        filename: "dwm-autostart-20161205-bb3bd6f.diff"
      }
    - {
        src: "https://dwm.suckless.org/patches/tilewide/dwm-tilewide-6.3.diff",
        filename: "dwm-tilewide-6.3.diff"
      }

- name: Aplica os patches
  shell: |
    cd "/home/{{ usuario }}/.config/suckless/dwm"
    patch < dwm-autostart-20161205-bb3bd6f.diff
    patch < dwm-tilewide-6.3.diff

- name: Copia o arquivo de configuração
  copy:
    src: config.def.h
    dest: /home/{{ usuario }}/.config/suckless/dwm
    owner: "{{ usuario }}"
    group: "{{ usuario }}"

- name: Compila o dwm
  shell: |
    cd "/home/{{ usuario }}/.config/suckless/dwm"
    make
    make clean install


