- name: Remove diretório do xmenu
  file:
    path: "/home/{{ usuario }}/.config/suckless/xmenu"
    state: absent
  become: yes
  become_user: root

- name: Clona o repositório do xmenu
  git:
    repo: https://github.com/phillbush/xmenu.git
    dest: /home/{{ usuario }}/.config/suckless/xmenu
    clone: yes
  become: yes
  become_user: "{{ usuario }}"

- name: Compila o dmenu
  shell: |
    rm -rf "/usr/local/bin/xmenu"
    cd "/home/{{ usuario }}/.config/suckless/xmenu"
    make all
    make install
    cp "/home/{{ usuario }}/.config/suckless/xmenu/examples/xmenu.sh" "/usr/local/bin/xmenu_iniciar"
    chmod +x "/usr/local/bin/xmenu_iniciar"
    chown {{ usuario }}:{{ usuario }} "/usr/local/bin/xmenu_iniciar"
    chown {{ usuario }}:{{ usuario }} "/usr/local/bin/xmenu"
