- name: Remove diretório do slock
  file:
    path: "/home/{{ usuario }}/.config/suckless/slock"
    state: absent
  become: yes
  become_user: root

- name: Clona o repositório slock
  git:
    repo: https://git.suckless.org/slock
    dest: /home/{{ usuario }}/.config/suckless/slock
    clone: yes
    force: yes
  become: yes
  become_user: "{{ usuario }}"

- name: Compila o slock
  shell: |
    rm -rf "/usr/local/bin/slock"
    cd /home/{{ usuario }}/.config/suckless/slock
    make
    make install
