- name: Configura o sudo
  user:
    name: "{{ usuario }}"
    groups: sudo
    append: yes
    createhome: yes
    password: "$6$vZoglp5i8xTPGdlI$3YVu35FUGUaXw5D8vQv7Y.NKrqK1sO.lJPih5UTKr4OSzdtrUkhjn1HBCiKr9PDG.sO4YnP9OGK/aAS9Svar51"
    shell: /bin/bash
  notify: Reinicia o lightdm

- name: Crie os diretórios principais
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
  loop:
    - "/home/{{ usuario }}/Downloads"
    - "/home/{{ usuario }}/Imagens"
    - "/home/{{ usuario }}/Música"
    - "/home/{{ usuario }}/Vídeos"
    - "/home/{{ usuario }}/Documentos"

- name: Instala as dependências
  apt:
    name:
    - x11-xserver-utils
    - make
    - gcc
    - libx11-dev
    - libxft-dev
    - libxinerama-dev
    - lightdm
    - unzip
    - ranger
    - libxrandr-dev
    - sudo
    - git
    - gpg
    - pavucontrol
    - pamixer
    - acpi
    - neofetch
    - htop
    - picom
    - numlockx
    - nitrogen
    - gh
    state: present
  become: yes
  become_user: root
