- name: Instala o chrome
  block:
  - name: adiciona chave gpg para repositório
    apt_key:
      url: "https://dl.google.com/linux/linux_signing_key.pub"
      state: present

  - name: adiciona repositório do google chrome
    apt_repository:
      filename: "google-chrome"
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      state: present

  - name: instala chrome
    apt:
      name:
        - google-chrome-stable

  - name: Instala VScode
    apt:
      deb: https://go.microsoft.com/fwlink/?LinkID=760868
      state: present
    become: yes

  