- name: Instala o tmux
  block:
  - name: Instala as dependências
    apt:
      name: tmux
      state: present
    become: yes
    become_user: root

  - name: Copia configuração do tmux
    copy:
      src: tmux_config
      dest: /home/{{ usuario }}/.tmux.conf
      owner: "{{ usuario }}"
      group: "{{ usuario }}"
