- name: Instala dependências do pyenv
  apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
  become: yes
  become_user: root

- name: Verificar se o diretório .pyenv existe
  stat:
    path: "/home/{{ usuario }}/.pyenv"
  register: resultado_stat

- name: Instala o pyenv se não estiver instalado
  shell: |
      curl https://pyenv.run | bash
  when: resultado_stat.stat.exists == False
      
- name: Configura o pyenv
  shell: |
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc
  become: yes
  become_user: "{{ usuario }}"
