- name: Altera permissões do diretório .config recursivamente
  file:
    path: /home/{{ usuario }}/.config
    state: directory
    recurse: yes
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
  
  
  