- name: Remove diretório do dmenu
  file:
    path: "/home/{{ usuario }}/.config/suckless/dmenu"
    state: absent
  become: yes
  become_user: root

- name: Clona o repositório do dmenu-5.2
  git:
    repo: https://github.com/Crystian0704/dmenu.git
    dest: /home/{{ usuario }}/.config/suckless/dmenu
    clone: yes

- name: Compila o dmenu
  shell: |
    rm -rf "/usr/local/bin/dmenu"
    cd "/home/{{ usuario }}/.config/suckless/dmenu"
    make
    make install


