- name: Instala as dependências
  apt:
    name:
      - make
      - gcc
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
    state: present
  become: yes

- name: Cria pasta .config no diretório do usuário se não existir
  file:
    path: /home/{{ user }}/.config
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Cria a pasta dmenu em .config
  file:
    path: /home/{{ user }}/.config/dmenu
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Faz o clone do repositório do dmenu
  git:
    repo: https://git.suckless.org/dmenu
    dest: /home/{{ user }}/.config/dmenu/
    owner: "{{ user }}"
    group: "{{ user }}"
    clone: yes

- name: Baixa os patches
  uri:
    url: { { item.src } }
    dest: /home/{{ user }}/.config/dmenu/{{ item.filename }}
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - {
        src: https://tools.suckless.org/dmenu/patches/center/dmenu-center-5.2.diff,
        filename: dmenu-center-5.2.diff,
      }
    - {
        src: https://tools.suckless.org/dmenu/patches/grid/dmenu-grid-4.9.diff,
        filename: dmenu-grid-4.9.diff,
      }
    - {
        src: https://tools.suckless.org/dmenu/patches/gridnav/dmenu-gridnav-5.2.diff,
        filename: dmenu-gridnav-5.2.diff,
      }
    - {
        src: https://tools.suckless.org/dmenu/patches/dracula/dmenu-dracula-20211128-d78ff08.diff,
        filename: dmenu-dracula-20211128-d78ff08.diff,
      }
    - {
        src: https://tools.suckless.org/dmenu/patches/border/dmenu-border-20230512-0fe460d.diff,
        filename: dmenu-border-20230512-0fe460d.diff,
      }
    - {
        src: https://tools.suckless.org/dmenu/patches/tsv/dmenu-tsv-20220305-e73651f.diff,
        filename: dmenu-tsv-20220305-e73651f.diff,
      }

- name: Aplica os patches
  shell: |
    cd /home/{{ user }}/.config/dmenu
    patch < dmenu-center-5.2.diff
    patch < dmenu-grid-4.9.diff
    patch < dmenu-tsv-20220305-e73651f.diff
    patch < dmenu-border-20230512-0fe460d.diff
    patch < dmenu-gridnav-5.2.diff
    patch < dmenu-dracula-20211128-d78ff08.diff

- name: Copia os arquivos de configuração para a pasta dmenu
  copy:
    src: files/
    dest: /home/{{ user }}/.config/dmenu/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Compila o dmenu
  shell: |
    cd /home/{{ user }}/.config/dmenu
    make clean install
