---
# vars file for vagrant_provision
vm_provision_numbers: 1
vm_provision_name: vm
vm_provision_box: debian/bookworm64
vm_provision_cidr_ip: 192.168.111 #format ip xxx.xxx.xxx
vm_provision_memory: 1024
vm_provision_cpus: 1
