- name: Executa as roles para configuração do desktop
  hosts: debian
  vars:
    usuario: crystian
  roles:
    - role: usuario
      tags: ['usuario']
    - role: dwm
      tags: ['dwm','wm']
    - role: st
      tags: ['st','wm']
    - role: dmenu
      tags: ['dmenu','wm']
    - role: slock
      tags: ['slock','wm']
    - role: dwmblocks
      tags: ['dwmblocks','wm']
    - role: fontes
      tags: ['fontes','wm']
    - role: tmux
      tags: ['tmux','wm']
    - role: chrome
      tags: ['chrome']
    - role: vscode
      tags: ['vscode']
    - role: trackpad
      tags: ['trackpad']
    - role: slstatus
      tags: ['slstatus']
    - role: pyenv
      tags: ['pyenv']

    
   




