- name: Executa as roles para configuração do desktop
  hosts: debian
  vars:
    usuario: oioi
  roles:
    - role: usuario
      tags: ['usuario']
    - role: dwm
      tags: ['dwm']
    - role: st
      tags: ['st']
    - role: dmenu
      tags: ['dmenu']
    - role: slock
      tags: ['slock']
    - role: dwmblocks
      tags: ['dwmblocks']
    - role: fontes
      tags: ['fontes']
   




